name = "autodev"
type = "javascript"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
  command = """
    corepack enable pnpm && \
    pnpm install && \
    pnpm run build
  """
  directory = "build/client"  # Ensure this is the right directory where your build output is stored
