name: Build and Publish to Cloudflare Pages

on:
  push:
    branches: main

jobs:
  build_and_publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build project
        run: |
          pnpm run build