name: Build and Publish to Cloudflare Pages
on:
  push:
    branches: main # modify the value if needed
jobs:
  build_and_publish:
    timeout-minutes: 10 # modify the value if needed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm pnpm-lock.yaml
          npm install -g pnpm
          pnpm install

      - name: Build project
        run: |
          pnpm run build